### ISSUE TITLE
Is the recorded result  the best one instead of average one?

### ISSUE THREAD

**Issue by WEIFZH** [DMIRLAB-Group/SASA#2]
Thanks for your wonderful work. When I run the code you provide, the result of the experiment (all the parameters are default) is not always as good as you recorded, i.e., as for quality prediction from Beijing to Tianjin, my best result is around 34.

**Comment by jozerozero** [comment]
Thanks for your attention. The published results are the best result we
achieved. There is some randomness. And 34 is also the normal result. We
will update the mean and the variance later. Thank you very much!

WEIFZH ***@***.***> 于2021年10月23日周六 下午9:51写道：

**Comment by WEIFZH** [comment]
Thanks for reply.
